environment:
  name: prod # prod, staging, dev, test, qa
  project: cdf-bootcamp-31-prod # ex. cdf-bootcamp-01-test
  validation-type: prod # prod, staging, dev, test, qa
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi 
      icapi_space_name: icapi_dm_space # the space we're pushing data to I think

      data_foundation:
        data_developer_source_id: aef78f03-6023-4c8d-bbeb-7ee0dad0d26f

      ice_cream_api:
        icapi_extractors_source_id: ed27adfe-b18d-4c7c-9096-949fc7b1093d

        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
#asdasd
      use_cases:
        oee:
          data_pipeline_oee_source_id: 407187a8-4b33-4377-9f23-0aa83898860a

          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}