environment:
  name: test # prod, staging, dev, test, qa
  project: cdf-bootcamp-31-test # ex. cdf-bootcamp-01-test
  validation-type: test # prod, staging, dev, test, qa
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi 
      icapi_space_name: icapi_dm_space # the space we're pushing data to I think

      data_foundation:
        data_developer_source_id: a29e505b-65e4-4c70-b5a8-3a5e13fb3d79

      ice_cream_api:
        icapi_extractors_source_id: 8844a15f-2d2c-4110-ac17-fe66b07fa31f

        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: e5dd3ee0-1620-43ce-a63e-b5da3639d669

          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}